apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
    app: {{ .Values.name }}
    chart: {{ template "entitlementpdp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  listenPort: {{ .Values.config.listenPort | quote }}
  externalHost: {{ .Values.config.externalHost | quote }}
  verbose: {{ .Values.config.verbose | quote }}
  disableTracing: {{ .Values.config.disableTracing | quote }}
  otlpCollectorEndpoint: {{ .Values.config.otlpCollectorEndpoint | quote }}
  opaConfigPath: {{ .Values.config.opaConfigPath | quote }}
  opa-config.yaml: |-
{{ toYaml .Values.opaConfigYaml | indent 4 }}
